service: chatscrum
# app and org for use with dashboard.serverless.com
app: chatscrum-app
org: adesanyajoshua

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Scan"
      Resource:
        - Fn::GetAtt: [ChatTable, Arn]
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"

functions:
  connectionHandler:
    handler: handler.connectionHandler
    events:
    - websocket:
        route: $connect
    - websocket:
        route: $disconnect
  defaultHandler:
    handler: handler.defaultHandler
    events:
    - websocket:
        route: $default
  sendMessageHandler:
    handler: handler.sendMessageHandler
    events:
      - websocket:
          route: sendMessage

resources:
  Resources:
    ChatTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "chatIdTable"
        AttributeDefinitions:
        - AttributeName: "connectionId"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "connectionId"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    MessageTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "MessageTable"
        AttributeDefinitions:
        - AttributeName: "messageid"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "messageid"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
